version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: ./
      - run:
          name: Build
          command: dotnet build --configuration Release --no-restore
          working_directory: ./
      - run:
          name: Running Tests
          command: dotnet test --no-restore --logger "trx"
          working_directory: OscCoreTests          
      - run:
          name: Test Results
          working_directory: ./
          command: |              
              export PATH="$PATH:/root/.dotnet/tools" && dotnet tool install -g trx2junit && trx2junit ./**/TestResults/*.trx
      - store_test_results:
          path: OscCoreTests/TestResults
      - store_artifacts:
          path: OscCoreTests/TestResults
          destination: TestResults
  publish-latest:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine
    steps:
      - run:
          name: Pack
          command: dotnet pack --no-build --no-restore --configuration Release
          working_directory: OscCore
      - run:
          name: Snitch
          command: find ./../../ | grep .nupkg
          working_directory: OscCore
workflows:
  version: 2
  build-master:
    jobs:
      - build    
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master          