version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: ./
      - run:
          name: Build
          command: dotnet build --configuration Release --no-restore
          working_directory: ./
      - run:
          name: Running Tests
          command: dotnet test --no-restore --logger "trx"
          working_directory: OscCoreTests          
      - run:
          name: Test Results
          working_directory: ./
          command: export PATH="$PATH:/root/.dotnet/tools" && dotnet tool install -g trx2junit && trx2junit ./**/TestResults/*.trx
      - store_test_results:
          path: OscCoreTests/TestResults
      - store_artifacts:
          path: OscCoreTests/TestResults
          destination: TestResults
      - run:
          name: Pack
          command: |
              mkdir ../.nuget
              dotnet pack --no-build --no-restore --configuration Release -o ../.nuget
          working_directory: OscCore
      - store_artifacts:
          path: ./.nuget
          destination: Nuget Packages    
      - save_cache:
          key: nuget-packages-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ./.nuget/    
          
  publish-latest:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine
    steps:
      - restore_cache:
            keys: nuget-packages-{{ arch }}-{{ .Branch }}-{{ .Environment.CIRCLE_SHA1 }}
      - run:
          name: Snitch
          command: find /root/ | grep .nupkg
          working_directory: ./
          
workflows:
  version: 2
  build-master:
    jobs:
      - build    
      - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: master          