version: 2
jobs:
  build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:2.2-alpine
    steps:
      - checkout
      - run:
          name: Restore
          command: dotnet restore
          working_directory: OscCore
      - run:
          name: Running Tests
          command: dotnet test
          working_directory: OscCoreTests
      - run:
          name: Build
          command: dotnet build -c Release
          working_directory: OscCore
